// <auto-generated />
using System;
using API_SystemSekolah.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APISystemSekolah.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_SystemSekolah.Models.Guru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_Of_Birth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Matpel")
                        .HasColumnType("int");

                    b.Property<string>("NIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoTelp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place_Of_Birth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Matpel");

                    b.ToTable("Gurus");
                });

            modelBuilder.Entity("API_SystemSekolah.Models.GuruRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Guru")
                        .HasColumnType("int");

                    b.Property<int>("Id_Roles")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Guru");

                    b.HasIndex("Id_Roles");

                    b.ToTable("GuruRoless");
                });

            modelBuilder.Entity("API_SystemSekolah.Models.JadwalMatpel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Kelas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Kelas");

                    b.ToTable("JadwalMatpels");
                });

            modelBuilder.Entity("API_SystemSekolah.Models.Kelas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kelass");
                });

            modelBuilder.Entity("API_SystemSekolah.Models.Matpel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Jadwal")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nilai_Harian")
                        .HasColumnType("int");

                    b.Property<int>("Nilai_UAS")
                        .HasColumnType("int");

                    b.Property<int>("Nilai_UTS")
                        .HasColumnType("int");

                    b.Property<int>("Nilai_rata_rata")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Jadwal");

                    b.ToTable("Matpels");
                });

            modelBuilder.Entity("API_SystemSekolah.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roless");
                });

            modelBuilder.Entity("API_SystemSekolah.Models.Siswa", b =>
                {
                    b.Property<int>("NIS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NIS"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_Of_Birth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Id_Kelas")
                        .HasColumnType("int");

                    b.Property<string>("Mother_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoTelp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place_Of_Birth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NIS");

                    b.HasIndex("Id_Kelas");

                    b.ToTable("Siswas");
                });

            modelBuilder.Entity("API_SystemSekolah.Models.Guru", b =>
                {
                    b.HasOne("API_SystemSekolah.Models.Matpel", "Matpels")
                        .WithMany()
                        .HasForeignKey("Id_Matpel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matpels");
                });

            modelBuilder.Entity("API_SystemSekolah.Models.GuruRoles", b =>
                {
                    b.HasOne("API_SystemSekolah.Models.Guru", "Gurus")
                        .WithMany()
                        .HasForeignKey("Id_Guru")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_SystemSekolah.Models.Roles", "Roless")
                        .WithMany()
                        .HasForeignKey("Id_Roles")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gurus");

                    b.Navigation("Roless");
                });

            modelBuilder.Entity("API_SystemSekolah.Models.JadwalMatpel", b =>
                {
                    b.HasOne("API_SystemSekolah.Models.Kelas", "Kelass")
                        .WithMany()
                        .HasForeignKey("Id_Kelas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kelass");
                });

            modelBuilder.Entity("API_SystemSekolah.Models.Matpel", b =>
                {
                    b.HasOne("API_SystemSekolah.Models.JadwalMatpel", "JadwalMatpels")
                        .WithMany()
                        .HasForeignKey("Id_Jadwal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JadwalMatpels");
                });

            modelBuilder.Entity("API_SystemSekolah.Models.Siswa", b =>
                {
                    b.HasOne("API_SystemSekolah.Models.Kelas", "Kelass")
                        .WithMany()
                        .HasForeignKey("Id_Kelas");

                    b.Navigation("Kelass");
                });
#pragma warning restore 612, 618
        }
    }
}
